<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Commission Invoice</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #333333;
            font-size: 11px;
            margin: 0;
            padding: 0;
        }
        .invoice-card {
            border: 2px solid #f5ab66;
            border-radius: 12px;
            padding: 20px;
            background-color: #ffffff;
        }
        /* mPDF safe alternative for badge */
        .badge-number {
            background-color: #e27d24;
            color: #ffffff;
            font-weight: bold;
            font-size: 14px;
            padding: 4px 10px;
            border-radius: 50%;
            display: inline;
        }
        .header-title-container {
            text-align: center;
            margin-bottom: 25px;
        }
        .main-header-title {
            color: #e27d24;
            font-size: 15px;
            font-weight: bold;
            margin: 0;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .sub-header-title {
            color: #666666;
            font-size: 11px;
            margin: 2px 0 0 0;
        }
        
        .w-100 { width: 100%; }
        .v-top { vertical-align: top; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        
        .brand-section {
            margin-bottom: 20px;
        }
        .logo-text {
            color: #0d3578;
            font-size: 20px;
            font-weight: bold;
        }
        .logo-subtext {
            color: #e27d24;
            font-size: 8px;
            letter-spacing: 1px;
            display: block;
            margin-top: -2px;
        }
        .invoice-meta-title {
            font-size: 14px;
            font-weight: bold;
            color: #222222;
            margin-bottom: 10px;
            text-transform: uppercase;
        }
        .meta-table td {
            padding: 2px 0;
            font-size: 11px;
        }
        .meta-label { color: #555555; }
        .meta-value { font-weight: bold; color: #111111; }

        /* Address Box styling */
        .billing-box {
            border-top: 1px solid #dddddd;
            border-bottom: 1px solid #dddddd;
            padding: 10px 0;
            margin-bottom: 15px;
            line-height: 1.5;
        }
        .billing-title {
            font-weight: bold;
            font-size: 11px;
            color: #111111;
            margin-bottom: 4px;
        }

        /* Items Grid styling */
        .items-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        .items-table th {
            border: 1px solid #999999;
            padding: 6px 8px;
            font-weight: bold;
            background-color: #f9f9f9;
            color: #111111;
        }
        .items-table td {
            border: 1px solid #999999;
            padding: 8px;
            font-size: 11px;
        }

        /* Financial Breakdown Tables */
        .breakdown-table {
            border-collapse: collapse;
            width: 100%;
        }
        .breakdown-table td {
            border: 1px solid #999999;
            padding: 5px 8px;
            font-size: 11px;
        }
        .bg-light { background-color: #f9f9f9; }
        .font-bold { font-weight: bold; }

        /* Footer Notes Area */
        .footer-notes {
            margin-top: 25px;
            line-height: 1.6;
            color: #333333;
        }
        .amount-words {
            font-size: 11px;
            margin-bottom: 12px;
        }
        .notice-text {
            color: #555555;
            font-size: 10px;
        }
        
        .computer-generated {
            text-align: center;
            color: #777777;
            font-size: 9px;
            margin-top: 25px;
        }
    </style>
</head>
<body>

    <div class="invoice-card">
        <!-- Top Badge Indicator -->
        <div style="margin-bottom: 10px;">
            <span class="badge-number"></span>
        </div>

        <!-- Document Main Header -->
        <div class="header-title-container">
            <h1 class="main-header-title">Apnifactory Commission Invoice</h1>
            <p class="sub-header-title">(Generated by ApniFactory)</p>
        </div>

        
        <table class="w-100 brand-section">
            <tr>
                <!-- Left Column Logo Brand -->
                <td class="v-top" style="width: 50%;">
                    <img src="https://panel.apnifactory.co.in/public/img/Apni-Factory-3.png" alt="Logo" width="200px">
                    <!--<div class="logo-text">🛒 ApniFactory</div>-->
                    <!--<span class="logo-subtext">FACTORY SE DIRECT</span>-->
                </td>
                <!-- Right Column Document Info Grid -->
                <td class="v-top text-right" style="width: 50%;">
                    <!--<div class="invoice-meta-title">Commission Invoice</div>-->
                    <table class="meta-table" align="right"> 
                        <tr>
                            <td class="meta-label text-right" style="padding-right: 8px;">Invoice No.</td>
                            <td class="meta-label">:</td>
                            <td class="meta-value text-right" style="padding-left: 5px;">{{ $invoice_no }}</td>
                        </tr>
                        <tr>
                            <td class="meta-label text-right" style="padding-right: 8px;">Invoice Date</td>
                            <td class="meta-label">:</td>
                            <td class="meta-value text-right" style="padding-left: 5px;">{{ $invoice_date }}</td>
                        </tr>
                        <tr>
                            <td class="meta-label text-right" style="padding-right: 8px;">Seller ID</td>
                            <td class="meta-label">:</td>
                            <td class="meta-value text-right" style="padding-left: 5px;">{{ $seller_id }}</td>
                        </tr>
                        <tr>
                            <td class="meta-label text-right" style="padding-right: 8px;">Order ID</td>
                            <td class="meta-label">:</td>
                            <td class="meta-value text-right" style="padding-left: 5px;">{{ $order_id }}</td>
                        </tr>
                        <tr>
                            <td class="meta-label text-right" style="padding-right: 8px;">Linked Invoice No.</td>
                            <td class="meta-label">:</td>
                            <td class="meta-value text-right" style="padding-left: 5px;">{{ $linked_invoice }}</td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>

        <!-- Billing Block -->
        <div class="billing-box">
            <div class="billing-title">Billed To (Seller)</div>
            <strong>{{ $seller_name }}</strong><br>
            {!! nl2br(e($seller_address)) !!}<br>
            <strong>GSTIN:</strong> {{ $seller_gstin }}
        </div>

        <!-- Items Grid Table -->
        <table class="items-table">
            <thead>
                <tr>
                    <th class="text-center" style="width: 10%;">Sl No.</th>
                    <th style="width: 55%;">Description of Service</th>
                    <th class="text-right" style="width: 35%;">Amount (₹)</th>
                </tr>
            </thead>
            <tbody>      <!-- Example item row for alignment stability -->
                <tr>
                    <td class="text-center">1</td>
                    <td>{{ $items["text"] }}<br><span>{{ $items["smalltext"] }}</span></td>
                    <td class="text-right">{{ number_format($subtotal, 2) }}</td>
                </tr>
            </tbody>
        </table>

        <!-- Summary & Totals Block Split Layout -->
        <table class="w-100" style="margin-top: 15px;">
            <tr>
                <!-- Left side message columns -->
                <td class="v-top" style="width: 50%; padding-right: 20px;">
                    <div class="amount-words" style="margin-top: 5px;">
                        <strong>Amount In Words:</strong><br>
                        <span style="font-style: italic; color: #555555;">{{ $amount_in_words }}</span>
                    </div>
                    <div class="notice-text">
                        This is our commission invoice for the above order.<br>
                        Please pay attention to your settlement statement for final payout details.
                    </div>
                </td>
                <!-- Right side calculation calculations -->
                <td class="v-top" style="width: 50%;">
                    <table class="breakdown-table">
                        <tr>
                            <td style="width: 60%;" class="text-right font-bold bg-light">Subtotal (₹)</td>
                            <td style="width: 40%;" class="text-right font-bold bg-light">{{ number_format($subtotal, 2) }}</td>
                        </tr>
                        <tr>
                            <td class="text-right">CGST @ 9% (₹)</td>
                            <td class="text-right">{{ number_format($cgst, 2) }}</td>
                        </tr>
                        <tr>
                            <td class="text-right">SGST @ 9% (₹)</td>
                            <td class="text-right">{{ number_format($sgst, 2) }}</td>
                        </tr>
                        <tr>
                            <td class="text-right font-bold bg-light">Total Invoice Value (₹)</td>
                            <td class="text-right font-bold bg-light">{{ number_format($total_value, 2) }}</td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>

       <div class="computer-generated">
            This is a computer-generated document and requires no physical signature.
        </div>
    </div>

</body>
</html>

